service: toniefy

image: benvp/toniefy

servers:
  - s03.benvp.co

registry:
  server: ghcr.io
  username: benvp
  password:
    - MRSK_REGISTRY_PASSWORD

env:
  clear:
    PORT: 3000
    PHX_HOST: tf.benvp.co
    UPLOAD_DIR: /app/storage/uploads
    TONIEX_RECORDER_URL: https://tf.benvp.co
    TONIEX_RECORDER_DOCKER_IMAGE_NAME: toniex_recorder:1.0.5
  secret:
    - SECRET_KEY_BASE
    - DATABASE_URL
    - MAILER_API_KEY
    - SPOTIFY_CLIENT_ID
    - SPOTIFY_CLIENT_SECRET

builder:
  dockerfile: "apps/toniefy/Dockerfile"
  context: "apps/toniefy"
  args:
    UPLOAD_DIR: /app/storage/uploads
  remote:
    arch: amd64
    host: ssh://root@s03.benvp.co

volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "/storage/toniefy/uploads:/app/storage/uploads"

accessories:
  postgres:
    image: postgres:15.3
    host: s03.benvp.co
    port: 5432
    env:
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_DB
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

healthcheck:
  path: /
  interval: 10s

labels:
  traefik.http.routers.toniefy.rule: Host(`tf.benvp.co`)
  traefik.http.routers.toniefy_secure.entrypoints: websecure
  traefik.http.routers.toniefy_secure.rule: Host(`tf.benvp.co`)
  traefik.http.routers.toniefy_secure.tls.certresolver: letsencrypt

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "hi@benvp.co"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
